const metrics = [
  {
    "id": "openrouter_tokens",
    "group": "AI Demand",
    "title": "OpenRouter 平台 token 用量趋势",
    "value": "51.4T",
    "unit": "7d",
    "change": "2026-07-05 to 2026-07-11",
    "trend": "up",
    "access": "自动",
    "cadence": "周",
    "source": "OpenRouter Datasets API",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "OpenRouter 平台口径，观察跨模型开发者调用需求，不代表全球 token 总量。"
  },
  {
    "id": "openrouter_share",
    "group": "AI Demand",
    "title": "OpenRouter 平台模型份额变化",
    "value": "69%",
    "unit": "Top10",
    "change": "Anthropic 14%",
    "trend": "flat",
    "access": "自动",
    "cadence": "周",
    "source": "OpenRouter Rankings",
    "sourceUrl": "https://openrouter.ai/rankings",
    "note": "Top10 模型集中度；第一模型：xiaomi/mimo-v2.5-20260422。"
  },
  {
    "id": "aa_value",
    "group": "AI Efficiency",
    "title": "Artificial Analysis 模型性价比",
    "value": "待接入",
    "unit": "",
    "change": "周频",
    "trend": "up",
    "access": "自动",
    "cadence": "周",
    "source": "Artificial Analysis API",
    "sourceUrl": "https://artificialanalysis.ai/api-reference",
    "note": "能力、价格、延迟、吞吐综合，用于判断 AI 使用成本。"
  },
  {
    "id": "cloudflare_ai_bots",
    "group": "AI Demand",
    "title": "Cloudflare AI crawler / bot traffic",
    "value": "待接入",
    "unit": "",
    "change": "月频",
    "trend": "flat",
    "access": "自动",
    "cadence": "周/月",
    "source": "Cloudflare Radar",
    "sourceUrl": "https://radar.cloudflare.com/ai-insights",
    "note": "观察 AI bot、crawler、agent 对互联网流量的影响。"
  },
  {
    "id": "anthropic_arr",
    "group": "AI Monetization",
    "title": "Anthropic ARR / run-rate",
    "value": "$47B",
    "unit": "annualized revenue",
    "change": "May 2026",
    "trend": "up",
    "access": "自动",
    "cadence": "事件/月",
    "source": "Sacra estimates",
    "sourceUrl": "https://sacra.com/c/anthropic/",
    "note": "自动抓取 Sacra 公司页中的 annualized revenue 估算。该项不是公司官方财报披露，适合做商业化方向性跟踪。"
  },
  {
    "id": "openai_arr",
    "group": "AI Monetization",
    "title": "OpenAI ARR / run-rate",
    "value": "$25B",
    "unit": "annualized revenue",
    "change": "February 2026",
    "trend": "up",
    "access": "自动",
    "cadence": "事件/月",
    "source": "Sacra estimates",
    "sourceUrl": "https://sacra.com/c/openai/",
    "note": "自动抓取 Sacra 公司页中的 annualized revenue 估算。该项不是公司官方财报披露，适合做商业化方向性跟踪。"
  },
  {
    "id": "ramp_ai_adoption",
    "group": "AI Monetization",
    "title": "Ramp 企业 AI 采用率",
    "value": "报告",
    "unit": "",
    "change": "月/季",
    "trend": "up",
    "access": "半自动",
    "cadence": "月/季",
    "source": "Ramp AI Index",
    "sourceUrl": "https://ramp.com/data/ai-index",
    "note": "用企业付款数据观察 AI 软件是否变成真实预算项。"
  },
  {
    "id": "msft_capex",
    "group": "AI Infrastructure",
    "title": "Microsoft CapEx",
    "value": "$28.1B",
    "unit": "FY2025",
    "change": "filed 2025-07-30",
    "trend": "up",
    "access": "自动",
    "cadence": "季",
    "source": "SEC / Microsoft IR",
    "sourceUrl": "https://www.microsoft.com/en-us/investor/default",
    "note": "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment."
  },
  {
    "id": "googl_capex",
    "group": "AI Infrastructure",
    "title": "Alphabet CapEx",
    "value": "$32.3B",
    "unit": "FY2025",
    "change": "filed 2026-02-05",
    "trend": "up",
    "access": "自动",
    "cadence": "季",
    "source": "SEC / Alphabet IR",
    "sourceUrl": "https://abc.xyz/investor/",
    "note": "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment."
  },
  {
    "id": "amzn_capex",
    "group": "AI Infrastructure",
    "title": "Amazon CapEx",
    "value": "$52.7B",
    "unit": "FY2025",
    "change": "filed 2026-02-06",
    "trend": "up",
    "access": "自动",
    "cadence": "季",
    "source": "SEC / Amazon IR",
    "sourceUrl": "https://ir.aboutamazon.com/overview/default.aspx",
    "note": "SEC companyconcept annual capex. Metric: PaymentsToAcquireProductiveAssets."
  },
  {
    "id": "meta_capex",
    "group": "AI Infrastructure",
    "title": "Meta CapEx",
    "value": "$27.0B",
    "unit": "FY2025",
    "change": "filed 2026-01-29",
    "trend": "up",
    "access": "自动",
    "cadence": "季",
    "source": "SEC / Meta IR",
    "sourceUrl": "https://investor.fb.com/",
    "note": "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment."
  },
  {
    "id": "nvda_dc_revenue",
    "group": "AI Revenue Check",
    "title": "NVIDIA data center revenue / guidance",
    "value": "季报",
    "unit": "",
    "change": "季频",
    "trend": "up",
    "access": "半自动",
    "cadence": "季",
    "source": "NVIDIA IR",
    "sourceUrl": "https://investor.nvidia.com/financial-info/quarterly-results/default.aspx",
    "note": "AI CapEx 转化为供应链收入的关键确认项。"
  },
  {
    "id": "ai_capex_roi",
    "group": "AI Stress",
    "title": "AI CapEx ROI 覆盖率",
    "value": "51.4%",
    "unit": "ARR / Big4 CapEx",
    "change": "ARR $72.0B / CapEx $140.1B",
    "trend": "flat",
    "access": "自动",
    "cadence": "季",
    "source": "Sacra estimates + SEC CapEx",
    "sourceUrl": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    "note": "第一版 ROI 代理：OpenAI + Anthropic annualized revenue 相对 Microsoft/Alphabet/Amazon/Meta 年度 CapEx。不是严格投资回报率，但能观察商业化收入相对资本开支的覆盖程度。"
  },
  {
    "id": "hyperscaler_capex_ocf_ratio",
    "group": "AI Cash Flow",
    "title": "云厂商 CapEx / 经营现金流",
    "value": "40.4%",
    "unit": "FY2026 CapEx / OCF",
    "change": "Amazon highest 62.1%",
    "trend": "up",
    "access": "自动",
    "cadence": "季/年",
    "source": "SEC companyconcept API",
    "sourceUrl": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    "note": "中金第二层现金流压力代理：Microsoft、Alphabet、Amazon、Meta、Oracle 年度资本开支相对经营性现金流。比例越高，说明内生现金流覆盖 AI 投资的余量越薄。"
  },
  {
    "id": "token_price_elasticity",
    "group": "AI Stress",
    "title": "Token 价格/用量弹性",
    "value": "价格未变",
    "unit": "",
    "change": "token 144.3% / price 0%",
    "trend": "flat",
    "access": "自动",
    "cadence": "周/月",
    "source": "OpenRouter + OpenRouter Models API",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "价格弹性 = token 用量变化率 / API 价格指数绝对变化率。价格不变时显示价格未变，继续积累历史。"
  },
  {
    "id": "llm_token_spend_index",
    "group": "AI Demand",
    "title": "LLM Token 支出指数",
    "value": "$2.22",
    "unit": "$/1M weighted",
    "change": "TTSI 101.1 / 28d 4.1%",
    "trend": "up",
    "access": "自动",
    "cadence": "日",
    "source": "TrakToken Spend Index",
    "sourceUrl": "https://www.traktoken.com/spend-index",
    "note": "TTSI 是 OpenRouter Top50 模型用量加权价格指数，混合价格采用 input 80% + output 20%，更贴近 coding agent 场景。CC BY 4.0。"
  },
  {
    "id": "frontier_premium",
    "group": "AI Demand",
    "title": "前沿模型价格溢价",
    "value": "11.3x",
    "unit": "frontier / open-weight",
    "change": "frontier $5.63 / open-weight $0.56",
    "trend": "up",
    "access": "自动",
    "cadence": "日",
    "source": "TrakToken Spend Index",
    "sourceUrl": "https://www.traktoken.com/spend-index",
    "note": "闭源前沿模型相对开源权重模型的用量加权价格溢价。溢价扩大说明高价值任务仍留在前沿模型；溢价收敛说明低成本模型替代压力增强。"
  },
  {
    "id": "free_token_share",
    "group": "AI Demand",
    "title": "免费 Token 占比",
    "value": "27.9%",
    "unit": "free token share",
    "change": "basket 40 models",
    "trend": "down",
    "access": "自动",
    "cadence": "日",
    "source": "TrakToken Spend Index",
    "sourceUrl": "https://www.traktoken.com/spend-index",
    "note": "TTSI 篮子里的免费 token 用量占比。若免费占比下降而总支出上升，说明支付意愿没有塌，更多是量补价和结构迁移。"
  },
  {
    "id": "token_arr_conversion",
    "group": "AI Monetization",
    "title": "Token / ARR 商业化效率",
    "value": "$26.9M",
    "unit": "ARR / annualized 1T OR tokens",
    "change": "ARR $72.0B / OR 2,672.8T annualized",
    "trend": "flat",
    "access": "自动",
    "cadence": "周/月",
    "source": "OpenRouter + Sacra estimates",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "商业化效率代理：OpenAI + Anthropic ARR 相对 OpenRouter token 年化用量。若 token 增速快于 ARR，该值会下行，提示低价值调用或价格竞争加剧。"
  },
  {
    "id": "ai_wage_pool_coverage",
    "group": "AI Social Cost",
    "title": "AI 暴露工资池覆盖率",
    "value": "5%",
    "unit": "ARR / exposed wage pool",
    "change": "theoretical pool 1.3%",
    "trend": "up",
    "access": "自动",
    "cadence": "月/事件",
    "source": "国金宏观 AI洪流三部曲 + Sacra estimates",
    "sourceUrl": "https://mp.weixin.qq.com/s/2MIroW_eh2hyaybRaACAXg",
    "note": "用文章中的美国 AI 实际暴露薪资池 $1.45T 和理论潜在薪资池 $5.68T 做分母，观察模型商 ARR 离“工资池重定价”还有多远。"
  },
  {
    "id": "tech_job_postings",
    "group": "AI Social Cost",
    "title": "软件开发岗位招聘指数",
    "value": 72.5,
    "unit": "Feb 2020=100",
    "change": "招聘平稳 / 28d -0.1%",
    "trend": "flat",
    "access": "自动",
    "cadence": "日/周",
    "source": "FRED / Indeed Hiring Lab",
    "sourceUrl": "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE",
    "note": "Indeed 美国软件开发岗位招聘指数，7日均值，2020-02-01=100。用来观察 AI 渗透和科技裁员叙事是否开始压低软件岗位需求。"
  },
  {
    "id": "hbm_dram_pressure",
    "group": "AI Stress",
    "title": "HBM/DRAM 价格压力指数",
    "value": "手动",
    "unit": "",
    "change": "月/季",
    "trend": "flat",
    "access": "手动",
    "cadence": "月/季",
    "source": "TrendForce / 存储厂财报",
    "sourceUrl": "https://www.trendforce.com/",
    "note": "监控 AI 抢产能是否从供应链利好变成消费电子需求破坏。"
  },
  {
    "id": "ai_crowding_unwind",
    "group": "AI Stress",
    "title": "AI 拥挤交易出清指数",
    "value": "待接入",
    "unit": "",
    "change": "周频",
    "trend": "flat",
    "access": "半自动",
    "cadence": "周",
    "source": "Mag 7 / SOXX / 等权标普",
    "sourceUrl": "https://www.spglobal.com/spdji/en/indices/equity/sp-500-equal-weight-index/",
    "note": "判断 AI 统一 beta 是否转向分化 alpha，市场是轮动还是坍塌。"
  },
  {
    "id": "ai_hardware_heat",
    "group": "AI Valuation Heatmap",
    "title": "AI 硬件上游拥挤温度",
    "value": "GPU/HBM",
    "unit": "最热",
    "change": "兑现交易",
    "trend": "flat",
    "access": "框架",
    "cadence": "周/月",
    "source": "AI产业链估值温度图",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "拥挤度排序：GPU > HBM > CoWoS/光模块 > ASIC > 云 > 模型 > Agent/应用。硬件上游已从景气交易进入兑现交易。"
  },
  {
    "id": "ai_downstream_odds",
    "group": "AI Valuation Heatmap",
    "title": "AI 下游三年赔率",
    "value": "Agent/应用",
    "unit": "最高",
    "change": "叙事交易",
    "trend": "up",
    "access": "框架",
    "cadence": "周/月",
    "source": "AI产业链估值温度图",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "三年赔率排序：Agent/应用 ≈ 基础模型 > ASIC/光互连 > 云厂商 > HBM > GPU。下一阶段机会来自 CapEx 继续上修或 Agent 收入爆发。"
  },
  {
    "id": "gpu_rental_price",
    "group": "AI Daily Core",
    "title": "GPU 租赁价格",
    "value": "$1.92/h",
    "unit": "H100 p25",
    "change": "H100 $1.92/h / H200 $3.75/h / B200 $7.51/h",
    "trend": "flat",
    "access": "自动",
    "cadence": "日/周",
    "source": "Vast.ai public offers API",
    "sourceUrl": "https://cloud.vast.ai/",
    "note": "自动抓取 Vast.ai verified rentable offers，按单 GPU 每小时价格计算 25 分位。它代表现货/长尾供给代理指标，不等同于大厂长期合约价。"
  },
  {
    "id": "api_price_index",
    "group": "AI Daily Core",
    "title": "主流模型 API 价格指数",
    "value": "$7.23",
    "unit": "$/1M blended",
    "change": "openai $7.38 / anthropic $19.0 / google $1.84 / deepseek $0.70",
    "trend": "down",
    "access": "自动",
    "cadence": "日/周",
    "source": "OpenRouter Models API",
    "sourceUrl": "https://openrouter.ai/api/v1/models",
    "note": "自动抓取 OpenRouter models pricing，按 OpenAI/Anthropic/Google/DeepSeek 各自付费文本模型的中位价格计算；blended = 30% input + 70% output。"
  },
  {
    "id": "agent_token_share",
    "group": "AI Daily Core",
    "title": "Agent Token 占比",
    "value": "待填",
    "unit": "%",
    "change": "周频",
    "trend": "up",
    "access": "手动",
    "cadence": "周",
    "source": "OpenRouter / Fireworks / 平台披露",
    "sourceUrl": "https://openrouter.ai/data",
    "note": "手动记录 OpenRouter、Fireworks 或平台披露中的 Agent Token 占比。"
  },
  {
    "id": "revenue_per_gpu",
    "group": "AI Daily Core",
    "title": "单位 GPU 每日收入",
    "value": "$46.1/day",
    "unit": "H100 spot proxy",
    "change": "median $51.3/day",
    "trend": "flat",
    "access": "自动",
    "cadence": "月/季",
    "source": "Vast.ai public offers API",
    "sourceUrl": "https://cloud.vast.ai/",
    "note": "第一版用 GPU 租赁现货价格估算单卡每日收入上限代理；后续可加入云厂商收入和 GPU 数量估算，提升为利润/ROI 指标。"
  }
];

module.exports = { metrics };
