const metrics = [
  { id: "openrouter_tokens", group: "AI Demand", title: "OpenRouter 平台 token 用量趋势", value: "46.7T", unit: "7d", change: "2026-06-22 to 2026-06-28", trend: "up", access: "缓存", cadence: "周", source: "OpenRouter Datasets API", sourceUrl: "https://openrouter.ai/data", note: "OpenRouter 平台口径，观察跨模型开发者调用需求，不代表全球 token 总量。" },
  { id: "openrouter_share", group: "AI Demand", title: "OpenRouter 平台模型份额变化", value: "66%", unit: "Top10", change: "Anthropic 13.6%", trend: "flat", access: "缓存", cadence: "周", source: "OpenRouter Rankings", sourceUrl: "https://openrouter.ai/rankings", note: "Top10 模型集中度；用于观察模型份额迁移。" },
  { id: "aa_value", group: "AI Efficiency", title: "Artificial Analysis 模型性价比", value: "待接入", unit: "", change: "周频", trend: "up", access: "自动", cadence: "周", source: "Artificial Analysis API", sourceUrl: "https://artificialanalysis.ai/api-reference", note: "能力、价格、延迟、吞吐综合，用于判断 AI 使用成本。" },
  { id: "cloudflare_ai_bots", group: "AI Demand", title: "Cloudflare AI crawler / bot traffic", value: "待接入", unit: "", change: "月频", trend: "flat", access: "自动", cadence: "周/月", source: "Cloudflare Radar", sourceUrl: "https://radar.cloudflare.com/ai-insights", note: "观察 AI bot、crawler、agent 对互联网流量的影响。" },
  { id: "anthropic_arr", group: "AI Monetization", title: "Anthropic ARR / run-rate", value: "手动", unit: "", change: "事件", trend: "up", access: "手动", cadence: "事件/月", source: "Sacra / The Information", sourceUrl: "https://sacra.com/c/anthropic/", note: "媒体估算口径，不等同审计收入，需要人工确认来源。" },
  { id: "openai_arr", group: "AI Monetization", title: "OpenAI ARR / run-rate", value: "手动", unit: "", change: "事件", trend: "up", access: "手动", cadence: "事件/月", source: "The Information / Sacra", sourceUrl: "https://www.theinformation.com/", note: "重点看消费者订阅、API、企业版和云分成。" },
  { id: "ramp_ai_adoption", group: "AI Monetization", title: "Ramp 企业 AI 采用率", value: "报告", unit: "", change: "月/季", trend: "up", access: "半自动", cadence: "月/季", source: "Ramp AI Index", sourceUrl: "https://ramp.com/data/ai-index", note: "用企业付款数据观察 AI 软件是否变成真实预算项。" },
  { id: "msft_capex", group: "AI Infrastructure", title: "Microsoft CapEx", value: "$28.1B", unit: "FY2025", change: "filed 2025-07-30", trend: "up", access: "缓存", cadence: "季", source: "SEC / Microsoft IR", sourceUrl: "https://www.microsoft.com/en-us/investor/default", note: "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment." },
  { id: "googl_capex", group: "AI Infrastructure", title: "Alphabet CapEx", value: "$32.3B", unit: "FY2025", change: "filed 2026-02-05", trend: "up", access: "缓存", cadence: "季", source: "SEC / Alphabet IR", sourceUrl: "https://abc.xyz/investor/", note: "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment." },
  { id: "amzn_capex", group: "AI Infrastructure", title: "Amazon CapEx", value: "$52.7B", unit: "FY2025", change: "filed 2026-02-06", trend: "up", access: "缓存", cadence: "季", source: "SEC / Amazon IR", sourceUrl: "https://ir.aboutamazon.com/overview/default.aspx", note: "SEC companyconcept annual capex. Metric: PaymentsToAcquireProductiveAssets." },
  { id: "meta_capex", group: "AI Infrastructure", title: "Meta CapEx", value: "$27.0B", unit: "FY2025", change: "filed 2026-01-29", trend: "up", access: "缓存", cadence: "季", source: "SEC / Meta IR", sourceUrl: "https://investor.fb.com/", note: "SEC companyconcept annual capex. Metric: PaymentsToAcquirePropertyPlantAndEquipment." },
  { id: "nvda_dc_revenue", group: "AI Revenue Check", title: "NVIDIA data center revenue / guidance", value: "季报", unit: "", change: "季频", trend: "up", access: "半自动", cadence: "季", source: "NVIDIA IR", sourceUrl: "https://investor.nvidia.com/financial-info/quarterly-results/default.aspx", note: "AI CapEx 转化为供应链收入的关键确认项。" },
  { id: "ai_capex_roi", group: "AI Stress", title: "AI CapEx ROI 覆盖率", value: "待建模", unit: "", change: "季频", trend: "flat", access: "半自动", cadence: "季", source: "大厂财报 / 10-Q / 电话会", sourceUrl: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces", note: "判断 AI 收入是否覆盖折旧、资本开支和现金流压力。" },
  { id: "token_price_elasticity", group: "AI Stress", title: "Token 价格/用量弹性", value: "待接入", unit: "", change: "周/月", trend: "flat", access: "自动", cadence: "周/月", source: "OpenRouter + Artificial Analysis", sourceUrl: "https://openrouter.ai/data", note: "验证模型降价是否带来足够多的 token 消费增长。" },
  { id: "hbm_dram_pressure", group: "AI Stress", title: "HBM/DRAM 价格压力指数", value: "手动", unit: "", change: "月/季", trend: "flat", access: "手动", cadence: "月/季", source: "TrendForce / 存储厂财报", sourceUrl: "https://www.trendforce.com/", note: "监控 AI 抢产能是否从供应链利好变成消费电子需求破坏。" },
  { id: "ai_crowding_unwind", group: "AI Stress", title: "AI 拥挤交易出清指数", value: "待接入", unit: "", change: "周频", trend: "flat", access: "半自动", cadence: "周", source: "Mag 7 / SOXX / 等权标普", sourceUrl: "https://www.spglobal.com/spdji/en/indices/equity/sp-500-equal-weight-index/", note: "判断 AI 统一 beta 是否转向分化 alpha，市场是轮动还是坍塌。" }
];

module.exports = { metrics };
